# Generated by Django 4.2.30 on 2026-07-27 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_app_name', models.CharField(max_length=100)),
                ('content_category', models.CharField(choices=[('insurance', 'Insurance'), ('ecommerce', 'E-commerce'), ('tech', 'Technology'), ('tourism', 'Tourism & Hospitality'), ('transportation', 'Transportation & Logistics'), ('retail', 'Retail'), ('finance', 'Banking & Finance')], max_length=50)),
                ('daily_traffic', models.BigIntegerField()),
                ('average_site_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bank_card_number', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('category', models.CharField(choices=[('insurance', 'Insurance'), ('ecommerce', 'E-commerce'), ('tech', 'Technology'), ('tourism', 'Tourism & Hospitality'), ('transportation', 'Transportation & Logistics'), ('retail', 'Retail'), ('finance', 'Banking & Finance')], max_length=50)),
                ('wallet_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
