# Generated by Django 4.2.30 on 2026-07-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='category',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('ecommerce', 'E-commerce'), ('tech', 'Technology'), ('tourism', 'Tourism & Hospitality'), ('logistics', 'Transportation & Logistics'), ('retail', 'Retail'), ('finance', 'Banking & Finance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='content_category',
            field=models.CharField(choices=[('sport', 'Sport'), ('news', 'News'), ('tech', 'Technology'), ('entertainment', 'Entertainment')], max_length=50),
        ),
    ]
