# Generated by Django 4.2.30 on 2026-07-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='destination_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
