# Generated by Django 4.2.30 on 2026-08-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_advertiser_category_and_more'),
        ('campaigns', '0002_alter_ad_destination_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaigns',
            new_name='Campaign',
        ),
        migrations.AlterField(
            model_name='ad',
            name='destination_url',
            field=models.URLField(max_length=500),
        ),
    ]
