# Generated by Django 4.2.30 on 2026-09-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_campaigns_campaign_alter_ad_destination_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to='ads/'),
        ),
    ]
