# Generated by Django 4.2.30 on 2026-08-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_rename_campaigns_campaign_alter_ad_destination_url'),
        ('accounts', '0002_alter_advertiser_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.ad')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.ad')),
                ('impression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.impression')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.publisher')),
            ],
        ),
    ]
